apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-prodcution-e2e-deployment
spec:
  selector:
    replica: 3
    matchLabels:
      app: complete-prodcution-e2e-app
  template:
    metadata:
      labels:
        app: complete-prodcution-e2e-app
    spec:
      containers:
        - name: complete-prodcution-e2e-app
          image: 894789/complete-prodcution-e2e-pipeline:1.0.0-32
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080